{
    'name': 'Custom WMS Base',
    'summary': 'Base customization for cross-border inventory workflows',
    'description': """
Base module for a lightweight cross-border purchase/sales/inventory setup.
Includes role groups and product customs fields used by downstream modules.
    """,
    'author': 'Lainey Team',
    'website': 'https://example.com',
    'category': 'Inventory/Inventory',
    'version': '19.0.1.0.0',
    'license': 'LGPL-3',
    'depends': [
        'product',
        'sale_management',
        'purchase',
        'stock',
        'stock_account',
    ],
    'data': [
        'security/wms_groups.xml',
        'security/wms_groups_update.xml',
        'security/ir.model.access.csv',
        'data/language_defaults.xml',
        'data/currency_activate.xml',
        'data/tax_data.xml',
        'data/customs_category_data.xml',
        'data/wms_onboarding_data.xml',
        'data/wms_cron.xml',
        'views/product_template_views.xml',
        'views/product_import_views.xml',
        'views/purchase_order_views.xml',
        'views/operation_control_views.xml',
        'views/wms_flow_step_views.xml',
        'views/res_users_views.xml',
        'views/wms_user_quick_create_views.xml',
        'views/wms_menus.xml',
        'views/wms_role_dashboard_views.xml',
        'views/wms_service_ticket_views.xml',
        'views/wms_usability_views.xml',
        'views/wms_reporting_views.xml',
        'views/wms_usability_enhancements_views.xml',
        'views/wms_onboarding_views.xml',
        'views/customs_category_views.xml',
        'data/wms_flow_step_data.xml',
    ],
    'installable': True,
    'application': False,
    'assets': {
        'web.assets_backend': [
            'custom_wms_base/static/src/scss/wms_theme.scss',
            'custom_wms_base/static/src/js/onboarding_systray.js',
            'custom_wms_base/static/src/xml/onboarding_systray.xml',
        ],
    },
}
