from . import product_template
from . import product_product
from . import res_users
from . import res_currency
from . import customs_category
from . import product_import_wizard
from . import wms_price_history
from . import wms_audit_log
from . import purchase_order
from . import sale_order
from . import stock_picking
from . import wms_stock_exception
from . import wms_stock_value_rank
from . import wms_daily_kpi
from . import wms_flow_step
from . import wms_service_ticket
from . import wms_role_dashboard
from . import wms_onboarding
from . import wms_language_defaults
from . import wms_user_quick_create
from . import wms_customer_contract
from . import wms_customer_order_wizard
